apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  ports:
    - port: 80
  selector:
    app: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  labels:
    account: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
    version: v1
spec:
  selector:
    matchLabels:
      app: admin
      version: v1
  template:
    metadata:
      labels:
        app: admin
        version: v1
    spec:
      containers:
        - image: oneadm/app:1.0
          imagePullPolicy: Always
          name: admin
          ports:
            - containerPort: 80
              name: http
